### ISSUE TITLE
Allow mixing order of options and positional arguments

### ISSUE THREAD

**Issue by joeltg** [sam701/zig-cli#11]
Right now, the first positional argument ends parsing of options, meaning that `./foo bar --baz` is parsed as two positional arguments `"bar"` and `"--baz"`, even if `--baz` is declared as a boolean option.

Is this intentional? Most tools accept options anywhere, especially at the end (useful for appending `--verbose` or similar without having to edit the previous command too much, etc).

If I understand the code right, deleting [this line](https://github.com/sam701/zig-cli/blob/4c790e926c5ad313a8a77c3aa34a32e89d531aad/src/parser.zig#L116) would continue parsing options after encountering the first positional argument (though I haven't tested this).

**Comment by sam701** [comment]
@joeltg Thank you for reporting! You are totally right, it is a bug. I will look into later today or on the weekend.
