### ISSUE TITLE
Nested subcommands cause infinite loop

### ISSUE THREAD

**Issue by rupurt** [sam701/zig-cli#42]
Nested subcommands render an infinite loop of no content. Is this meant to be supported?

**Comment by sam701** [comment]
Could you paste your `main.zig` and elaborate a bit on your use case so that we are on the same page?

**Comment by rupurt** [comment]
Sorry, my bad. I ended up finding the issue. It wasn't related to nested subcommands. I had an empty `.options = &.{},` which was causing the issues. When I removed that it was fine.
