### ISSUE TITLE
thread 1862 panic: unable to find module 'zig-cli'

### ISSUE THREAD

**Issue by segersniels** [sam701/zig-cli#44]
Not sure if directly related to GitHub issues but it seems like Actions are now failing due to them not being able to find the `zig-cli` module. It's kind of a blackbox since it still works locally on my machine to build.

I see that the Actions of the standalone example also started failing today. Pretty new to Zig as a whole and especially `zon` so haven't been able to dig deep into it.

**Comment by sam701** [comment]
Yeah, I couldn't reproduce this error locally with the same zig version as used in the github actions (`zig-zig-linux-x86_64-0.12.0-dev.3533+e5d900268`) either. I will look into over the weekend.

**Comment by sam701** [comment]
That's not quite true what I wrote. I tested on `aarch64`. The github actions run on `x86_64`...

**Comment by sam701** [comment]
It is not related to the CPU architecture. It depends on the `~/.cache/zig`. The build fails when the directory does not exist. But it compiles on the second try. Here is the related issue in `zig` https://github.com/ziglang/zig/issues/19561

**Comment by segersniels** [comment]
That's odd, but great find! Zig must have broken something in one of the latest releases then.

**Comment by sam701** [comment]
The zig issue was fixed and the `zig-cli` jobs are back to green.
