### ISSUE TITLE
short.exe leading to segmentation error on win11

### ISSUE THREAD

**Issue by F2011B** [sam701/zig-cli#47]
The example short.exe can be compiled, 
however on windows 11 with 
zig-windows-x86_64-0.13.0
I receive a segmentation error calling the executable with 
_.\zig-out\bin\short.exe  --port=12 --host=123_
_Segmentation fault at address 0x2206b980153_
In case i call it in the following way no segmentation error is thrown.
 _.\zig-out\bin\short.exe  --port=12_
_debug: server is listening on localhost_
Therefore the treatment of the host variable seems to be faulty.

**Comment by sam701** [comment]
Unfortunately, I do not have any windows system I can test on. I cannot reproduce this behaviour on macos or linux. We need to wait for someone who could look into on Windows.

**Comment by erik-dunteman** [comment]
Thanks for this fix @F2011B 

For anyone reading this in the future needing this fix in a zig 0.13 compatible version (per #50), I set up a fork applying these changes to the `last-zig-0.13` branch

https://github.com/pig-dot-dev/zig-cli
